services:
  emailproxy:
    build: .
    image: fawad-imap-proxy:latest
    container_name: fawad-imap-proxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:1143:1143"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./emailproxy.config:/config/emailproxy.config:rw
      - tokenstore:/config/tokens
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  tokenstore:
    driver: local
